### ISSUE TITLE
Build a n-D universal estimator

### ISSUE THREAD

**Issue by yossi-cohen** [yossi-cohen/preferential-attachment#21]
# Universal estimator

Let  𝑓 (𝑥 | 𝑑1,...,𝑑𝑛)  be a function, that for any fixed values of the parameters  𝑑𝑖 , reduces to a PDF of x;  𝑓  thus is a family of functions, e.g., log normal.

## Task
write a *universal estimator*
𝑒𝑠𝑡𝑖𝑚𝑎𝑡𝑜𝑟 ( 𝑓, 𝑠𝑎𝑚𝑝𝑙𝑒)  is a function that learns the parameters 𝑑𝑖 of 𝑓 from a single input sample (𝑚 observations drawn using 𝑓).

- [ ] Apply 2D  range adjustment; for now, it will be independent parameters: should adjust to (-0.5,0.5)^2 (n=2) in this case: we want the range to be an n-dimensional unit cube; this makes it easier to understand subranges. 0.1-0.2. We also introduce some "prior" in a very convoluted way. A priori, the range is -infinity to +infinity. And we know nothing about where the parameter is.
After range adjustment, we shrink some regions by a large factor and others by a small factor. So, we favor the center of the range,  We may even beat Cramer Rao for this reason. 

- [ ] Select 5 or so longtail distributions. (We may need to change the families later). Do range adjustment, and it should be sensible in the sense that it is approximately centered. 
- [ ]   do range adjustment (orthogonal for now, i.e, independently for each original parameter)
- [ ] draw a mesh on the unit square, say with a resolution of 0.1, this gives 81 points for each mesh. Maybe 1/11 resolution? Maybe include the last and first row and column. 
- [ ] For each point in the mesh, run learning experiment producing:
   - Several (say 10-100) learning experiments. without focusing for now.
   - Compute the average error of the 10-100 experiments. MSE rules
   - Compute the Cramer Rao bound (numerically if the analytical solution is not possible)
   - Divide the MSE by Cramer Rao.
  
 

- [ ] Draw the 3D manifold on the mesh.

Expected results:

1. Hopefully, we are at most 2 times worse than CR. 
2. Hopefully, the CR is never singular, i.e. not zero nor infinity.

More work?

- 3D?
- More balanced distributions?
- Strange combinations, i.e., log normal with Yule, with some constraints on the parameters.

**Comment by yossigil** [comment]
Explore focussing if we do not reach the CR bound.
